### ISSUE TITLE
Website looks bad

### ISSUE THREAD

**Issue by TheVirtualMachine** [mcpt/mcpt.github.io#11]
### Who are you

I am:
- [x] An official member of the MCPT website development process
- [ ] Just someone who wants to help

----------------------------------------

### Issue
The website design looks awful.

### Pages affected
- all of them

**Comment by TheVirtualMachine** [comment]
@djacewicz @angela-wang1 You guys are going to fix this.

**Comment by Jeffmagma** [comment]
Right now, the dropdown looks really ugly, maybe remove the lines, unround the corners, and add a shadow similar to the one in the header?  
Also, personally i think it would look better if the cell changed background color instead of underlined on hover

**Comment by TheVirtualMachine** [comment]
Dropdown menus don't make sense on mobile, so I've redone the mobile navigation menu.

**Comment by angela-wang1** [comment]
Question: Are we allowed to upload the CPT group photo onto the website? Or executive pictures? (I remember asking Ms. Krasteva a few months ago but I forgot what she said, if no one knows, I'll ask her on Monday). Our current Meet the Execs page looks very plain with an overflow of words so some pictures would be a nice balance, but if those aren't allowed, I can rearrange the page too seem more appealing (Maybe even include department names e.g. Teaching as a way to sort).

**Comment by TheVirtualMachine** [comment]
I'm not sure if pictures are allowed, but feel free to check.

**Comment by angela-wang1** [comment]
Sure I'll check monday

**Comment by angela-wang1** [comment]
@shannonoh335 Can you contribute to this website looking bad issue as well..

**Comment by Ninjaclasher** [comment]
Since we are redesigning the website completely, can this be closed?

**Comment by ehhthing** [comment]
Closed because of redesign.
