### ISSUE TITLE
Redundant Page

### ISSUE THREAD

**Issue by angela-wang1** [mcpt/mcpt.github.io#12]
### Who are you

I am:
- [x] An official member of the MCPT website development process
- [ ] Just someone who wants to help

----------------------------------------

### Issue
After clicking "Learn ICS" there's no point in having "Lessons" and nothing else, just go directly to lessons that get displayed: Basic and Advanced. That is unless there is something that needs to be added but has not been yet. 

### Pages affected
- ics
- ics-lessons

### Mockups
Here's the empty looking page I'm talking about:

![screen shot 2017-12-16 at 2 03 48 pm](https://user-images.githubusercontent.com/28734899/34073551-1a510b76-e26a-11e7-8691-72152efac75c.png)

Why not just go directly to this

![screen shot 2017-12-16 at 2 04 00 pm](https://user-images.githubusercontent.com/28734899/34073550-14e0640c-e26a-11e7-936b-f9d54d11202e.png)

**Comment by TheVirtualMachine** [comment]
We were planning to have problems later as well, but we can have it go directly to the lessons until we do that.

**Comment by TheVirtualMachine** [comment]
Fixed.

**Comment by angela-wang1** [comment]
It's still there, was that intentional? @TheVirtualMachine 
![screen shot 2018-01-06 at 12 34 27 am](https://user-images.githubusercontent.com/28734899/34636921-7081d696-f279-11e7-8e8a-4b8136559870.png)

After "Lessons" is clicked:
![screen shot 2018-01-06 at 12 35 33 am](https://user-images.githubusercontent.com/28734899/34636927-8be8b120-f279-11e7-898a-13cc81f08679.png)

**Comment by TheVirtualMachine** [comment]
The lessons link was left in so as not to break any previous bookmarks or links. I will look into setting up an alias, if I cannot, that will have to remain.

**Comment by TheVirtualMachine** [comment]
This can be done using the Jekyll redirect plugin.

https://help.github.com/articles/redirects-on-github-pages/

@Jeffmagma I'd like you to take this one.

**Comment by TheVirtualMachine** [comment]
The commits referenced above should solve this. I'll need to test it is correctly synced up with mcpt.ca. If not, I'll have to find a workaround.

**Comment by TheVirtualMachine** [comment]
And it does not work.

I swear that at least 90% of our technical problems are because we're using GoDaddy for hosting.

**Comment by TheVirtualMachine** [comment]
This will be fixed when #18 is completed.
