### ISSUE TITLE
Creating Learn menu and CPT/ICS submenus

### ISSUE THREAD

**Issue by angela-wang1** [mcpt/mcpt.github.io#13]
### Who are you

I am:
- [x] An official member of the MCPT website development process
- [ ] Just someone who wants to help

----------------------------------------

### Issue
Can we combine "Learn CPT" and "Learn ICS" under one menu: "Learn", but have submenus called "CPT" and "ICS"..content stays the same
![screen shot 2018-01-06 at 12 52 55 am](https://user-images.githubusercontent.com/28734899/34637069-ffd27bb4-f27b-11e7-8b56-9918d021474f.png)

### Pages affected
- Learn CPT
- Learn ICS

**Comment by TheVirtualMachine** [comment]
This is a good idea. I'd like to see it done with purely CSS, no libraries.

It's possible with clever use of the `:hover` pseudoclass and the CSS `display` property.

**Comment by TheVirtualMachine** [comment]
I'm assigning @djacewicz (David) to this.

@angela-wang1 you mean it should be a dropdown menu?

**Comment by angela-wang1** [comment]
Yeah, drops down when the mouse hover's over "Learn" E.g:

![screen shot 2018-01-06 at 2 11 35 pm](https://user-images.githubusercontent.com/28734899/34643064-ae140f70-f2eb-11e7-9483-df320da8c575.png)

**Comment by TheVirtualMachine** [comment]
Okay. I'll leave some links here for @djacewicz.

https://developer.mozilla.org/en-US/docs/Web/CSS/:hover
https://developer.mozilla.org/en-US/docs/Web/CSS/display
https://www.w3schools.com/Css/css_dropdowns.asp
