### ISSUE TITLE
Why the extra Moose link?

### ISSUE THREAD

**Issue by angela-wang1** [mcpt/mcpt.github.io#14]
### Who are you

I am:
- [x] An official member of the MCPT website development process
- [ ] Just someone who wants to help

----------------------------------------

### Issue
I realize Moose contest is already over, but still --> "Moose contest" hidden at the bottom of the calendar on the Members page isn't needed since it's already one of the menus on the top of the page 

![screen shot 2018-01-06 at 1 01 02 am](https://user-images.githubusercontent.com/28734899/34637159-c6b6a3e4-f27d-11e7-9d48-be2efccf6865.png)

### Pages affected
-members

**Comment by TheVirtualMachine** [comment]
I'll remove all the Moose related pages, as that contest is over.
