### ISSUE TITLE
4 spaced tabs

### ISSUE THREAD

**Issue by Jeffmagma** [mcpt/mcpt.github.io#2]
can we have 4 spaced tabs (it's 8 right now) so code doesn't become extremely long

**Comment by TheVirtualMachine** [comment]
I will take a look at this. While I prefer 8 spaces for the reasons mentioned in the kernel style guide, I agree that competition programming (and certain languages) require different conventions.

**Comment by TheVirtualMachine** [comment]
Should be an easy fix.

https://developer.mozilla.org/en-US/docs/Web/CSS/tab-size#Browser_compatibility

I have no problem not fully supporting IE or Edge. I doubt we have many users of those browsers anyways.
