### ISSUE TITLE
Ownership of the organization needs to be changed

### ISSUE THREAD

**Issue by mcpt-larry** [mcpt/mcpt.github.io#22]
### Who are you

I am:
- [X] An official member of the MCPT website development process.
- [ ] Just someone who wants to help.

----------------------------------------

### Issue
Currently, the owners/people in this organization/repository no longer run the Mackenzie Computer Programming Team, the organization's ownership should be transferred to the new presidents (@richardyi25, @LevelRaisin...)

**Comment by TheVirtualMachine** [comment]
Richard and Lev are already owners of the organization.
